// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_shutdown_screen_screen_init(void)
{
    ui_shutdown_screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_shutdown_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_shutdown_screen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_shutdown_screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_turnoffslider = lv_slider_create(ui_shutdown_screen);
    lv_slider_set_value(ui_turnoffslider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_turnoffslider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_turnoffslider, 0,
                                                                                                  LV_ANIM_OFF);
    lv_obj_set_width(ui_turnoffslider, 280);
    lv_obj_set_height(ui_turnoffslider, 45);
    lv_obj_set_x(ui_turnoffslider, 0);
    lv_obj_set_y(ui_turnoffslider, 100);
    lv_obj_set_align(ui_turnoffslider, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_turnoffslider, lv_color_hex(0x424242), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_turnoffslider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_turnoffslider, lv_color_hex(0x424242), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_turnoffslider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_turnoffslider, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_turnoffslider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_turnoffslider, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_turnoffslider, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_turnoffslider, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_turnoffslider, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_turnoffslider, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_turnoffslider, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_turnoffslider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_turnoffslider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);


}
