// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_label_speed = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_label_speed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_speed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_label_speed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label_speed, "49");
    lv_obj_set_style_text_color(ui_label_speed, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label_speed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label_speed, &ui_font_bebas120, LV_PART_MAIN | LV_STATE_DEFAULT);


}
