#include <stdio.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "nvs_flash.h"
#include "esp_log.h"
#include "ble_spp_client.h"
#include "adc.h"
#include "lcd.h"
#include "driver/gpio.h"
#include "esp_sleep.h"
#include "sleep.h"
#include "button.h"
#include "ui/ui.h"  // Generated by SquareLine Studio
#include "vesc_config.h"
#include "main.h"
#include "viber.h"
#include "hw_config.h"
#include "lis3dhtr.h"
#include "battery.h"
#include "tp_button.h"

#define TAG "MAIN"

#define BLE_TASK_PRIORITY         9
#define ADC_TASK_PRIORITY         10
#define DISPLAY_UPDATE_PRIORITY   5
#define SLEEP_MONITOR_PRIORITY    4

extern bool is_connect;

// Global mutex definitions
SemaphoreHandle_t lvgl_mutex = NULL;
SemaphoreHandle_t ble_data_mutex = NULL;
SemaphoreHandle_t adc_mutex = NULL;

void init_system_mutexes(void) {
    lvgl_mutex = xSemaphoreCreateMutex();
    ble_data_mutex = xSemaphoreCreateMutex();
    adc_mutex = xSemaphoreCreateMutex();

    if (!lvgl_mutex || !ble_data_mutex || !adc_mutex) {
        ESP_LOGE(TAG, "Failed to create mutexes");
        abort();
    }
}


static void splash_timer_cb(lv_timer_t * timer) {
    // Switch from splash screen to home screen
    lv_disp_load_scr(ui_home_screen);
    //Delete the timer since we only need it once
    if (timer != NULL) {
        lv_timer_del(timer);
    }
}

void app_main(void)
{
    // Initialize sleep module
    sleep_init();

    // Initialize system mutexes
    init_system_mutexes();

    // Initialize NVS
    esp_err_t ret = nvs_flash_init();
    if (ret == ESP_ERR_NVS_NO_FREE_PAGES || ret == ESP_ERR_NVS_NEW_VERSION_FOUND) {
        ESP_ERROR_CHECK(nvs_flash_erase());
        ret = nvs_flash_init();
    }
    ESP_ERROR_CHECK(ret);

    // Initialize VESC configuration
    ESP_ERROR_CHECK(vesc_config_init());

    // Turn on hall sensor
    gpio_set_level(HALL_SENSOR_VDD_PIN, 1);

    // Initialize ADC and start tasks
    ESP_ERROR_CHECK(adc_init());
    adc_start_task();

    // Wait for ADC calibration
    while (!adc_is_calibrated()) {
        vTaskDelay(pdMS_TO_TICKS(100));
    }

    // Initialize BLE
    spp_client_demo_init();
    ESP_LOGI(TAG, "BLE Initialization complete");

    // Initialize Viber
    ESP_ERROR_CHECK(viber_init());

    // Initialize battery monitoring
    ESP_ERROR_CHECK(battery_init());
    battery_start_monitoring();

    ESP_LOGI(TAG, "Initializing display");
    ESP_ERROR_CHECK(display_init());

    // Initialize touch buttons
    esp_err_t tp_ret;
    int tp_retry_count = 0;
    const int MAX_TP_RETRIES = 3;

    do {
        tp_ret = tp_button_init();
        if (tp_ret != ESP_OK) {
            ESP_LOGW(TAG, "Touch button initialization failed, retry %d", tp_retry_count + 1);
            vTaskDelay(pdMS_TO_TICKS(500));
        }
        tp_retry_count++;
    } while (tp_ret != ESP_OK && tp_retry_count < MAX_TP_RETRIES);

    if (tp_ret != ESP_OK) {
        ESP_LOGE(TAG, "Touch button initialization failed after %d retries", MAX_TP_RETRIES);
        // Handle the error (maybe restart the device)
        esp_restart();
    }

    vTaskDelay(pdMS_TO_TICKS(50));

    ui_init();

    vTaskDelay(pdMS_TO_TICKS(50));

    lv_disp_load_scr(ui_splash_screen);
    lv_timer_t *splash_timer = lv_timer_create(splash_timer_cb, 3000, NULL);
    lv_timer_set_repeat_count(splash_timer, 1);

       // Start button monitoring
    sleep_start_monitoring();

    viber_play_pattern(VIBER_PATTERN_SINGLE_SHORT);

  // Initialize accelerometer
    ret = lis3dhtr_init();
    if (ret == ESP_ERR_NOT_FOUND) {
        ESP_LOGW(TAG, "Accelerometer not found - continuing without accelerometer functionality");
    } else if (ret != ESP_OK) {
        ESP_LOGE(TAG, "Accelerometer initialization failed with error %d", ret);
    }
    xTaskCreate(lis3dhtr_task, "lis3dhtr_task", 4096, NULL, 5, NULL);

    // Keep main task alive with minimal CPU usage
    while(1) {
        vTaskDelay(pdMS_TO_TICKS(100));
    }
}

